#
# Publishing OpenWRT package
#

name: Package publisher

permissions:
    contents: write

on:
  push:
    tags:
      - v1.**

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      OWRTSDK: openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64

    steps:
    - name: Install required packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: |
          build-essential ccache ecj fastjar file g++ gawk
          gettext git java-propose-classpath libelf-dev libncurses5-dev
          libncursesw5-dev libssl-dev python3 unzip wget
          python3-distutils python3-setuptools python3-dev rsync subversion
          swig time xsltproc zlib1g-dev

    - name: Restore OpenWRT SDK from cache
      id: cache-owrtsdk-restore
      uses: actions/cache/restore@v3
      with:
        path: build
        key: openwrt-sdk-22.03.5

    - name: Download OpenWRT SDK
      if: steps.cache-owrtsdk-restore.outputs.cache-hit != 'true'
      run: |
        mkdir build
        cd build
        wget -q https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/${OWRTSDK}.tar.xz
        tar -xf ${OWRTSDK}.tar.xz
        rm ${OWRTSDK}.tar.xz

    - name: Cache OpenWRT SDK
      id: cache-owrtsdk-save
      uses: actions/cache/save@v3
      with:
        path: build
        key: openwrt-sdk-22.03.5
    
    - name: Git configuration
      run: git config --global advice.detachedHead false

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        path: feed/persistent-tty
        
    - name: Build pakage
      run: |
        cd build
        echo 'src-link perstty ${{ github.workspace }}/feed' > ${OWRTSDK}/feeds-perstty.conf
        cp ${{ github.workspace }}/feed/persistent-tty/openwrt/diffconfig ${OWRTSDK}
        cp ${{ github.workspace }}/feed/persistent-tty/openwrt/build-perstty-workflow.sh ${OWRTSDK}/build-perstty.sh
        cd ${OWRTSDK}
        ./build-perstty.sh
        PKG_VER=${{ github.ref }}
        PKG_VER=${PKG_VER##refs/tags/v}
        if [ -z $(ls bin/packages/*/perstty/persistent-tty_${PKG_VER}-*.ipk) ]; then
           echo '::error::Package not found'
           exit 1
        fi

    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          build/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64/bin/packages/*/perstty/*.ipk
