#
# Publishing OpenWRT package
#

name: Package bublisher

permissions:
    contents: write

on:
  push:
    tags:
      - v1.**

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        OWRTSDK: openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64

    steps:
    - name: Install required packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: |
          build-essential ccache ecj fastjar file g++ gawk
          gettext git java-propose-classpath libelf-dev libncurses5-dev
          libncursesw5-dev libssl-dev python3 unzip wget
          python3-distutils python3-setuptools python3-dev rsync subversion
          swig time xsltproc zlib1g-dev

    - name: Git configuration
      run: git config --global advice.detachedHead false

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        path: persistent-tty
        
    - name: Build pakage
      run: |
        mkdir ../build
        cd ../build
        wget -q https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/${OWRTSDK}.tar.xz
        tar -xf ${OWRTSDK}.tar.xz
        rm ${OWRTSDK}.tar.xz
        echo 'src-link perstty ${{ github.workspace }}' > ${OWRTSDK}/feeds-perstty.conf
        cp ${{ github.workspace }}/persistent-tty/openwrt/diffconfig ${OWRTSDK}
        cp ${{ github.workspace }}/persistent-tty/openwrt/build-perstty.sh ${OWRTSDK}
        cd ${OWRTSDK}
        ./build-perstty.sh
        PKG_VER=${{ github.ref }}
        PKG_VER=${PKG_VER##refs/tags/v}
        if [ -z $(ls bin/packages/*/perstty/persistent-tty_${PKG_VER}-*.ipk) ]; then
           echo 'Package not found'
           exit 1
        fi

    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ../build/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64/bin/packages/*/perstty/*.ipk
